---
kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64
steps:
  - name: build
    image: gradle:8.0.2
    commands:
      - gradle build
  - name: publish
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      registry: docker.io
      username:
        from_secret: registry_username
      password:
        from_secret: registry_pwd
      repo: maxdistructo2/platinum
      tags:
        - latest
      platforms:
        - linux/arm64
        - linux/amd64
trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request
