FROM eclipse-temurin:21.0.4_7-jdk-jammy
WORKDIR /opt/platinum
RUN echo "1.1" > version
RUN apt update
RUN apt install git tesseract-ocr -y
RUN git clone https://github.com/MaxDistructo/platinum
WORKDIR /opt/platinum/platinum
RUN git checkout main
RUN chmod +x gradlew
RUN ./gradlew build
WORKDIR /opt/platinum
RUN cp /opt/platinum/platinum/build/libs/platinum.jar /opt/platinum/platinum.jar
RUN rm -rf /opt/platinum/platinum
